import { chromium } from 'playwright'
const OUT = '/tmp/claude-0/demo/shots'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const page = await browser.newPage({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 2 })
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
await page.fill('input[name="email"]', 'pm@ridgeline.test')
await page.fill('input[name="password"]', 'plumbline-demo')
await page.getByRole('button', { name: 'Sign in' }).click()
await page.waitForTimeout(3000)
await page.getByText('Harbor Point Phase II').first().click()
await page.waitForTimeout(3000)
await page.getByText('Records', { exact: true }).first().click()
await page.waitForTimeout(2200)
await page.screenshot({ path: `${OUT}/07-records-list.png` })
console.log('LIST', (await page.locator('body').innerText()).slice(0, 1200))
await browser.close()
