import { chromium } from 'playwright'
const OUT = '/tmp/claude-0/demo/shots'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const page = await browser.newPage({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 2 })
page.on('pageerror', (e) => console.log('PAGEERROR', String(e).slice(0, 300)))
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
await page.fill('input[name="email"]', 'pm@ridgeline.test')
await page.fill('input[name="password"]', 'plumbline-demo')
await page.getByRole('button', { name: 'Sign in' }).click()
await page.waitForTimeout(3000)
await page.getByText('Harbor Point Phase II').first().click()
await page.waitForTimeout(3000)
await page.getByText('Records', { exact: true }).first().click()
await page.waitForTimeout(2200)
await page.locator('tbody tr').filter({ hasText: 'Anchor bolt' }).first().click()
await page.waitForTimeout(2500)
console.log('H1', await page.locator('h1').first().innerText())
await page.screenshot({ path: `${OUT}/08-record-detail.png` })
await page.getByRole('tab', { name: /Attachments/ }).click()
await page.waitForTimeout(1500)
await page.screenshot({ path: `${OUT}/09-attachments.png` })
console.log('ATTACH', (await page.locator('body').innerText()).slice(-400))
await browser.close()
